In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
def read_csv(file_path):
  df = pd.read_csv(file_path)
  X = np.array(df["sentence"])
  Y = np.array(df["label"])
  return X,Y

In [3]:
X_train , Y_train = read_csv("/content/dataset_Emoji_Text_Classification/train.csv")
X_test , Y_test = read_csv("/content/dataset_Emoji_Text_Classification/test.csv")


In [9]:
index = 7
X_train[index], Y_train[index]

('congratulations on your acceptance', 2)

In [13]:
def label_to_emoji(label):
    emojies = ["❤️", "🏐", "😄", "😞", "🍴"]
    return emojies[label]

index = 7
print(X_train[index], label_to_emoji(Y_train[index]))

congratulations on your acceptance 😄


In [ ]:
len(np.unique(Y_train))

In [11]:
unique,counts = np.unique(Y_train, return_counts=True)
print(unique)
print(counts)

[0 1 2 3 4]
[22 19 38 36 17]


In [ ]:
max_len = len(max(X_train , key=len).split(" "))
print(max_len)

In [ ]:
!wget https://nlp.stanford.edu/data/glove.6B.zip
!unzip -q glove.6B.zip -d /content/drive/MyDrive/dataset/glov.6b

In [49]:
 f = open("/content/drive/MyDrive/dataset/glov.6b/glove.6B.50d.txt", encoding="utf_8")

In [50]:
word_vectoros = {}
for line in f:
  line = line.strip().split()
  word = line[0]
  vector= np.array(line [1:], dtype=np.float64)
  word_vectoros[word] = vector

In [51]:
word_vectoros["programming"]

array([ 0.14957 , -0.16036 , -0.1369  ,  1.0076  , -0.37291 ,  0.63466 ,
       -0.93203 , -1.5188  , -0.24924 ,  0.67075 ,  0.51193 ,  0.28389 ,
        0.18781 ,  0.8798  , -0.023971,  0.39789 , -0.72769 ,  1.0153  ,
        0.11723 , -0.14114 ,  0.974   ,  0.48037 ,  0.25464 ,  1.3262  ,
        0.17958 ,  0.19717 ,  0.074712, -0.24844 ,  0.26248 , -0.084427,
        3.156   ,  0.38308 , -0.095827, -0.99383 , -0.20497 ,  0.38918 ,
       -0.13281 , -0.21775 , -0.93632 ,  0.37943 ,  0.78475 ,  0.36969 ,
       -1.3904  ,  0.54891 , -1.3798  ,  0.18898 ,  0.60928 ,  0.98271 ,
       -0.53934 ,  1.4439  ])

In [62]:
def senteence_to_avg(sentence):
  try:
    sentence = sentence.lower()# uper
    words = sentence.strip().split(" ")
    sum_vectors = np.zeros((50, ))
    for word in words :
      sum_vectors += word_vectoros[word]


    avg_vectors = sum_vectors / len(words)
    return avg_vectors
  except:
    print(sentence)
    return None

In [63]:
senteence_to_avg("i love programming")

array([ 0.04320667,  0.37743   , -0.357031  , -0.00865333,  0.38053333,
        0.32633333, -0.52007333, -0.3322732 , -0.52798   ,  0.58148919,
        0.03828333,  0.69974667, -0.48341333,  0.09162733,  0.708883  ,
        0.22826333, -0.12114   ,  0.59850333,  0.02376167, -0.31820967,
        0.02860333,  0.86243333,  0.55779667,  0.68638667,  0.93642667,
       -1.27037667, -0.85302933,  0.01946667,  0.77329333, -0.735489  ,
        3.1286    ,  0.58391   , -0.37328233, -0.15569   , -0.26527   ,
       -0.05288667,  0.04671   ,  0.02445333, -0.19468333, -0.19417333,
        0.28425557,  0.05271067, -0.61895333,  0.31371333, -0.36647133,
        0.19412333,  0.163318  , -0.32117   , -0.36403667,  0.88497   ])

In [64]:
#X_trin_avg =[]
#for x_train in X_train :
#  X_trin_avg.append(senteence_to_avg(x_train))
#X_trin_avg = np.array(X_trin_avg)

#X_trin_avg.shape


X_train_avg = []
for x_train in X_train:
  X_train_avg.append(senteence_to_avg(x_train))

X_train_avg = np.array(X_train_avg)

X_train_avg.shape


(132, 50)

In [ ]:
Y_train_on_hot = tf.keras.utils.to_categorical(Y_train,num_classes=5)
Y_train_on_hot

In [67]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(5, input_shape=(50,),activation='softmax')

])

In [68]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [69]:
model.fit(X_train_avg , Y_train_on_hot,epochs=200)

Epoch 1/200
5/5 [==============================] - 1s 11ms/step - loss: 1.9217 - accuracy: 0.1288
Epoch 2/200
5/5 [==============================] - 0s 4ms/step - loss: 1.8814 - accuracy: 0.1515
Epoch 3/200
5/5 [==============================] - 0s 6ms/step - loss: 1.8478 - accuracy: 0.1591
Epoch 4/200
5/5 [==============================] - 0s 3ms/step - loss: 1.8153 - accuracy: 0.1591
Epoch 5/200
5/5 [==============================] - 0s 3ms/step - loss: 1.7866 - accuracy: 0.1515
Epoch 6/200
5/5 [==============================] - 0s 3ms/step - loss: 1.7619 - accuracy: 0.1667
Epoch 7/200
5/5 [==============================] - 0s 3ms/step - loss: 1.7380 - accuracy: 0.1742
Epoch 8/200
5/5 [==============================] - 0s 3ms/step - loss: 1.7162 - accuracy: 0.1742
Epoch 9/200
5/5 [==============================] - 0s 3ms/step - loss: 1.6946 - accuracy: 0.1742
Epoch 10/200
5/5 [==============================] - 0s 4ms/step - loss: 1.6758 - accuracy: 0.2197
Epoch 11/200
5/5 [==========

In [70]:
my_test ="lest play ball"
my_test_avg = senteence_to_avg(my_test)
my_test_avg = np.array([my_test_avg])
result = model.predict(my_test_avg)
y_perd = np.argmax(result)
label_to_emoji(y_perd)

1/1 [==============================] - 0s 80ms/step


'🏐'